### ISSUE TITLE
Issue Warning on Encrypted Stored Procs/Functions

### ISSUE THREAD

**Issue by wdiplacidosm** [GoEddie/SQLCover#1]
I was running Get-CoverTSql on a database that contains some business logic. There were several encrypted procedures (most were unencrypted) and the Get-CoverTSql command would not finish its execution. It took a while to trace it back to the fact that the batches.Add (line 63 in DatabaseSourceGateway.cs) was throwing an error when it tried to parse the encrypted object.

**Comment by GoEddie** [comment]
Hey, thanks for reporting this - I have added a fix to skip any sql_modules (procs etc) where we aren't given / allowed the definition:

https://github.com/GoEddie/SQLCover/blob/encrypted-procs/src/SQLCover/releases/SQLCover.0.2.1.zip?raw=true

There is also an additional property on the $result object called "Warnings" - can you let me know if this sorts if for you?

**Comment by wdiplacidosm** [comment]
Hi GoEddie, no problem. Thanks for the quick response. Everything is working well now. I ran version 0.2.1 and do see warning messages:

Warnings
--------
The object definition for [dbo].[GetStatus] was not found, unable to provide code coverage resultsThe object definition for [dbo].[GetUpdates] was not found...

Also was able to produce reports with ReportGenerator.exe.

My only comment would be to insert some CRLF's between each warning.

Regards,

Bill

**Comment by GoEddie** [comment]
Great, good point about the line break I will add it in.
