### ISSUE TITLE
MIT or apache 2.0 licence?

### ISSUE THREAD

**Issue by Seddryck** [GoEddie/SQLCover#11]
The project page on GitHub is referencing both (MIT and Apache 2.0) licence. Can we use both licences?

![sql-cover-licence](https://cloud.githubusercontent.com/assets/5455045/21940065/cefde370-d9c2-11e6-8cde-18c51c07ca4d.jpg)

**Comment by GoEddie** [comment]
The project is Apache 2.0 :) if this causes anyone an actual problem let me know.
