### ISSUE TITLE
[BUG] Timeout error "Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding"

### ISSUE THREAD

**Issue by Radamonas** [GoEddie/SQLCover#27]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
The build is executed on build machine is failing with error message 
_2018-02-27T16:36:32.6985021Z Starting code coverage...
2018-02-27T16:37:07.3044875Z ##[error]Exception calling "Cover" with "1" argument(s): "Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding._

Output from the tests was shown in the output of the build, so the execution was not stuck.
I ran with 'exec tSQLt.RunAll'

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com/
N/A

**What is the expected behavior?**
Expecting to have this step finished within a longer period than it is hardcoded in the code.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL2008R2
Win2012
TFS2015
This error was noticed on the first run.

**Comment by MarekMasko** [comment]
Timeout threshold is by default set to 30 seconds, but this can be changed. 
You can do it by providing the second parameter for `Cover()` method. The second parameter is a query timeout in seconds. If you set it to 0, then there will be no timeout. 

The easiest way to do it is to replace 
`$coverage.Cover($query)`
with 
`$coverage.Cover($query,0)`

in SQLCover.ps1 file.

**Comment by Radamonas** [comment]
@MarekMasko thanks for the provided example, this helped me to solve the time out issue. Closing this bug.
