### ISSUE TITLE
Branch coverage is zero 

### ISSUE THREAD

**Issue by ronniekapoor** [GoEddie/SQLCover#28]
Bug

Upon using SqlCover with tSqlT, the line coverage is found but the branch coverage is zero

Using the way mentioned in this link
https://the.agilesql.club/2016/04/sqlcover-code-coverage-for-sql-server-t-sql/

**Comment by GoEddie** [comment]
Hi @ronniekapoor I need a bit more to go on, if you can give me an example of what you mean then please re-open this!

ed
