### ISSUE TITLE
Getting error: Write-Error "Redgate SQLRelease Module missing."

### ISSUE THREAD

**Issue by yakubpasha02** [GoEddie/SQLCover#29]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com/

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by yakubpasha02** [comment]
Hi,
I am currently working on setting up SQL Code Coverage. I used the script available and created a powershell build step in team city. Prior to that, I have installed SQL Change Automation tool in the server. When I tried to execute the powershell script, I am getting an error mentioned above. I checked in the powershell modules listing and not able to see the "SQLRelease" module. Could you please help me how I would be able to enable this module in the server.
Thanks for your help in advance.

**Comment by GoEddie** [comment]
Hi @yakubpasha02 if you have a problem with the redgate tools then contact their very helpful support support@redgate.com
