### ISSUE TITLE
misleading success when tsqlt test command timeouts

### ISSUE THREAD

**Issue by aboatswain** [GoEddie/SQLCover#3]
I think this should be flaged as a failure, currently it continues and shows the coverage on what did end up running before the timeout, you would not notice unless you had debugging on.

**Comment by GoEddie** [comment]
agreed!

**Comment by GoEddie** [comment]
Timeouts are now reported by crashing the coverage:

https://github.com/GoEddie/SQLCover/releases/tag/v0.4-test
