### ISSUE TITLE
Inline Table Valued Functions

### ISSUE THREAD

**Issue by silverbullettruck2001** [GoEddie/SQLCover#30]
When I have a tSQLt test that is written to test an inline table function there is no coverage results provided for any of the tests for that function.  Please let me know if there is anything I need to provide to assist with resolving this issue.  I am using Red Gate's SQL Test product that now uses SQL Cover so I am not very familiar with this specific project but was told that this was the best place to report this issue.

Thanks,

Adam

**Comment by RobClenshaw** [comment]
It looks like SQL Server extended events doesn't register an event when the object is an inline table valued function. This means there's nothing for SQL Cover to pick up, so that's why there is no coverage result. This may be a SQL Server bug.

**Comment by GoEddie** [comment]
Hi @silverbullettruck2001 Rob is right, we aren't notified by sql that the inline tvf was called.

I have created a "Feature Request" issue and added it to this, it isn't possible to get it working with the current version but might work in a future version.

https://github.com/GoEddie/SQLCover/issues/34
