### ISSUE TITLE
Error starting trace: System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired. 

### ISSUE THREAD

**Issue by stefanievario** [GoEddie/SQLCover#39]
This is an awesome tool.  We have been using it for a while now and it is really helping us in our CI/CD efforts.   We have several databases that are local and SQL Cover works very well.  Other databases are remote and we get timeout errors when it is trying to start the SQL trace.   Is there a way to change the SQL timeout?  It appears to default to 30 seconds.   

Here is the snippet of code we are using to call SQL Cover: 

	$connection = New-Object System.Data.SqlClient.SqlConnection
	$connection.ConnectionString = "server=our_server;database=our_database;integrated security=SSPI;"
	Add-Type -Path D:\SQLCover\SQLCover\SQLCover.dll
	$coverage = new-object SQLCover.CodeCoverage($connection.ConnectionString, $connection.Database, $true, $true) 

        ######## This is where it times out. #######
	$status = $coverage.Start(); 
        #########################

        #Execute the unit tests here  (using VSTest) 

        $coverageResults = $coverage.Stop()

Thank you for a great product!

**Comment by GoEddie** [comment]
I'll include a fix in the next release :)

**Comment by GoEddie** [comment]
Timeouts are configurable as of 0.5.0 - you can include "Connect Timeout=xx" in the connection string and `Start(int timeout = 30)` accepts a timeout in seconds and defaults to 30 seconds.

https://github.com/GoEddie/SQLCover/releases/tag/0.5.0

**Comment by stefanievario** [comment]
Thank you so much!

Stefanie Vario
Data Architect – Application Development

[MOTOR]<http://motor.com/>

MOTOR Information Systems
1301 W. Long Lake Road, Suite 300 | Troy, MI 48098

[MOTOR]<http://motor.com/>  [Facebook] <http://facebook.motor.com/>   [Twitter] <http://twitter.motor.com/>   [LinkedIn] <http://linkedin.motor.com/>   [YouTube] <http://youtube.motor.com/>
