### ISSUE TITLE
Clustered Index coverage

### ISSUE THREAD

**Issue by surbhi05** [GoEddie/SQLCover#41]
Hi Team,

I have a stored procedure which creates a table variable with a clustered index.

SQLCover doesn't give the code coverage for it. Please suggest how to cover that statement.

Please refer the screenshot below
![ClusteredIndexIssue](https://user-images.githubusercontent.com/29044661/62115769-97246100-b2d6-11e9-8781-f31e405bf14f.png)

Thanks.
Surbhi Jain

**Comment by GoEddie** [comment]
hmmm, this should be ignored as I make declare statments as not coverable statement.

leave it with me and i'll put in a fix for it.

**Comment by GoEddie** [comment]
Hi,

I can't reproduce this, can you test with 0.5.0 and see if it still happens?

https://github.com/GoEddie/SQLCover/releases/tag/0.5.0

If it does can you re-open and give me an example of a procedure that causes it?

thanks
