### ISSUE TITLE
.Net core support (linux)

### ISSUE THREAD

**Issue by GoEddie** [GoEddie/SQLCover#53]
do it!

**Comment by lastlink** [comment]
* well I have a deploy that works using dotnet core and github actions see #58

**Comment by lastlink** [comment]
* github actions is in the correct direction. #54 isn't tested and should not be merged.
* also comment from https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/issues/49 for tsql testing. it appears w/ already existing tools that if we use a tsql dacpac then it may be possible to publish on dotnet core.
* I think this should be tested against sql server 2019 docker image for best results. But if it builds in github actions and generates coverage then this ticket can be closed. I may look into this in the next few weeks if it's not too big a task.
