### ISSUE TITLE
Extended Event logs are not cleaned up when running against a remote server

### ISSUE THREAD

**Issue by jmclusky** [GoEddie/SQLCover#6]
When running against a remote server, the extended event log file is not cleaned up properly. This is because the Drop method in SqlTraceController assumes that the tool is running on the local SQL Server and just deletes from the local filesystem, leaving the .xel files in place on the remote server.

Short of using xp_cmdshell or similar there's not much that could be done to resolve this other in SQLCover itself, but it is probably worth noting this in documentation to ensure that people are prepared.

**Comment by GoEddie** [comment]
Agreed, I need to sort out the documentation for this and a few other things, happy to accept pr's to the README :)

**Comment by GoEddie** [comment]
I have added a note in the readme about this :)
