### ISSUE TITLE
DeclareTableVariableStatement statements cannot be covered, so report falsely as missing coverage

### ISSUE THREAD

**Issue by jmclusky** [GoEddie/SQLCover#7]
The statement type DeclareTableVariableStatement cannot be covered and does not appear in the extended events files so causes a false report of uncovered code. It should be added to the cases in StatementParser.CanBeCovered.

**Comment by GoEddie** [comment]
cool i'll add this when I do the next build :)

**Comment by jmclusky** [comment]
Great, thanks!

**Comment by jmclusky** [comment]
The pull request accepted yesterday resolves this issue, so this can now be closed.
