### ISSUE TITLE
News about release 0.6 or what's next?

### ISSUE THREAD

**Issue by cagrin** [GoEddie/SQLCover#75]
Any news about release 0.6 or SQLCover version that works cross-platform?

It would be awesome to push it even further to the .NET 6.

@GoEddie - Please give us your thoughts about future maintaining SQLCover project.

**Comment by lastlink** [comment]
@cagrin this is already cross platform (sql server only). Just look at the GitHub actions and the SQLCover core project. It's in .net3.1. That's cross platform. It's open sourced if you want a newer .net core version do a pr or clone and run it locally with a new version.
